/* ------------------------------------------------------------------ *
 * Tests for typing text at a TUI (api/src/tui-input.mjs) — the sanitiser, the
 * read-back gate, and the verified box clear.
 *
 * TWO incidents are pinned here.
 *
 * 1. THE SWALLOW. Both executors type a prompt at the agent with
 *    `tmux send-keys -l`, which is a KEYBOARD. A pasted terminal excerpt still
 *    carries the escapes the chat view rendered invisibly, so Claude Code's
 *    input parsed them as key input — and an OSC introducer consumes everything
 *    up to its terminator. Reproduced live: 427 B typed, 77 chars landed, 350
 *    characters of the operator's sentence gone; the trailing Enter then
 *    submitted the residue as their message, and the model answered it.
 *
 * 2. THE GATE'S OWN REGRESSION. The first read-back gate was head-anchored
 *    against the WHOLE pane. Measured live (80 columns, pane heights 24/40/80):
 *    the input box CAPS at 7-8 rows and SCROLLS, so a 672-char note shows only
 *    its LAST 7 rows and its head is not on the pane at all — refused, always.
 *    Above ~900 chars the box collapses to `[Pasted text #N]`, which the gate
 *    accepted. So every payload in a ~500-900 char window was refused whatever
 *    it contained: 24 consecutive `deliver-mangled` at 3 s intervals,
 *    `len:678 stripped:0` (no escapes at all). And the refusal's clear COUNTED
 *    presses while `C-u` kills one DISPLAY ROW — so each refusal left a row of
 *    the head behind and the next attempt typed 678 more characters onto it:
 *    65 → 134 → 198 → 267 chars, concatenated mid-word, ending in a submit.
 *
 * The panes below are generated by FakeBox, which encodes exactly that measured
 * mechanism — so the fixtures and the failure model cannot drift apart.
 *
 * Run: node --test api/test/tui-input.test.mjs
 * ------------------------------------------------------------------ */
import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  sanitizeForTyping,
  deliveryLanded,
  inputBoxText,
  clearInputBox,
  TUI_CLEAR_KEY,
  TUI_CLEAR_MAX_PRESSES,
  TUI_VERIFY_MAX_CHARS,
} from '../src/tui-input.mjs'

/* ── The measured box ───────────────────────────────────────────────────────
 * `C-u` removes ONE display row (not the logical line), typing APPENDS at the
 * cursor, and the box renders only its last CAPACITY rows. An EMPTY box is not
 * blank: idle it draws a rotating hint in SGR 2, and typed text is never faint
 * — which is the property that separates "empty" from "residue".
 */
const COLS = 78, CAPACITY = 7
class FakeBox {
  constructor(content = '') { this.content = content; this.presses = 0 }
  rows() { return this.content.match(new RegExp(`.{1,${COLS}}`, 'g')) || [] }
  type(text) { this.content += text }
  pressClear() { const r = this.rows(); this.presses++; this.content = r.slice(0, -1).join('') }
  render() {
    const shown = this.rows().slice(-CAPACITY)
    const body = shown.length ? shown.map((r, i) => (i ? '  ' : '❯ ') + r) : ['\x1b[39m❯ \x1b[2mTry "how do I log an error?"\x1b[0m']
    return ['─'.repeat(80), ...body, '─'.repeat(80), '  ⏵⏵ bypass permissions on'].join('\n')
  }
  io() { return { readPane: async () => this.render(), pressClear: async () => this.pressClear(), settle: async () => {} } }
}
const boxWith = (content) => new FakeBox(content).render()
// A BUSY empty box draws nothing but the `❯` marker (no faint hint).
const EMPTY_BUSY_BOX = ['─'.repeat(80), '❯ ', '─'.repeat(80), '  ⏵⏵ bypass permissions on · esc to interrupt'].join('\n')

// The turn-end note the incident refused 24 times, at the same size (672-702
// chars) and the same shape. Exactly 9 display rows wide, so the counted-clear
// arithmetic below is the incident's arithmetic.
const NOTE = (() => {
  let s =
    '⏸ Turn ended — the dev agent you spawned on demo-app (agent-7 — "add a health endpoint") ' +
    'has gone IDLE after a 4m turn and is now waiting at its prompt. This answers no message ' +
    'of yours — it is what the dashboard observed. Read its transcript (or ask it) for what ' +
    'it did and whether it is blocked. One line per turn it finishes — this is not a status feed. '
  while (s.length < 9 * COLS) s += 'Nothing else is queued behind it. '
  return s.slice(0, 9 * COLS)
})()

const PROSE =
  'I noticed that after a successful /compact the chat view produces a couple of stray ' +
  'messages, some of them carrying command-name tags — can we fix that?'
const ARTIFACT = 'Compacted (ctrl+o to see full summary)</local-command-stdout>"'
const PAYLOAD = `${PROSE} Example: ${ARTIFACT}`

/* --- 1. the sanitiser: never lose a printable character ---------------- */

test('an UNTERMINATED OSC keeps every printable character — the incident', () => {
  // A partial copy that starts inside an OSC-8 hyperlink: no BEL follows, so a
  // terminal swallows to the end of the payload. We must not.
  const typed = `\x1b]8;id=1pv6qjt;file:///srv/demo-app/x${PROSE} Example: \x1b[2m${ARTIFACT}`
  const safe = sanitizeForTyping(typed)
  assert.ok(safe.includes(PROSE), "the operator's sentence must survive")
  assert.ok(safe.includes(ARTIFACT), 'the pasted example must survive')
  assert.ok(!safe.includes('\x1b'), 'no ESC may reach the pane')
  // The lone introducer loses only its ESC; its printable remnant stays visible
  // rather than eating what follows. Ugly beats lost.
  assert.ok(safe.startsWith(']8;id=1pv6qjt;file:///srv/demo-app/x'))
})

test('a well-formed OSC-8 hyperlink is removed whole, its link text kept', () => {
  const typed = 'see \x1b]8;id=1;file:///srv/demo-app/note.md\x07note.md\x1b]8;;\x07 for details'
  assert.equal(sanitizeForTyping(typed), 'see note.md for details')
})

test('CSI colour codes are removed, the text between them is not', () => {
  const typed = `<local-command-stdout>\x1b[2mCompacted\x1b[22m</local-command-stdout>"`
  const safe = sanitizeForTyping(typed)
  assert.ok(!safe.includes('\x1b'))
  assert.ok(!safe.includes('[2m') && !safe.includes('[22m'))
  assert.equal(safe, '<local-command-stdout>Compacted</local-command-stdout>"')
})

test('a lone ESC drops only itself — the terminal would eat the next key too', () => {
  assert.equal(sanitizeForTyping('abc\x1bCompacted'), 'abcCompacted')
})

test('newlines and tabs survive; CR and CRLF normalise to one newline', () => {
  assert.equal(sanitizeForTyping('a\nb\tc'), 'a\nb\tc')
  assert.equal(sanitizeForTyping('a\r\nb\rc'), 'a\nb\nc')
})

test('other C0 controls are dropped without touching text', () => {
  assert.equal(sanitizeForTyping('a\x00b\x07c\x7fd'), 'abcd')
})

test('ordinary text is returned byte-identical', () => {
  const plain = `${PROSE}\n\nsecond paragraph with accents: äöü — and a [[wikilink]].`
  assert.equal(sanitizeForTyping(plain), plain)
  assert.equal(sanitizeForTyping(''), '')
  assert.equal(sanitizeForTyping(undefined), '')
})

/* --- 2. the read-back gate --------------------------------------------- */

test('an EMPTY box reads empty — bare `❯ ` (busy) and the faint placeholder (idle)', () => {
  assert.equal(inputBoxText(EMPTY_BUSY_BOX), '')
  assert.equal(inputBoxText(boxWith('')), '')
})

test('THE REGRESSION: a scrolled 9-row note lands — head off-screen, box full', () => {
  const p = boxWith(NOTE)
  assert.ok(!p.includes(NOTE.slice(0, 40)), "the note's HEAD is not on the pane at all")
  const shown = inputBoxText(p)
  assert.ok(shown.length > 0 && shown.length < NOTE.replace(/\s+/g, '').length, 'only the tail is visible')
  assert.equal(deliveryLanded(p, NOTE), true, 'the shipped gate refused this 24 times in 75 s')
})

test('…and it lands on a BUSY pane too — boundary delivery must keep working', () => {
  // Text sitting in the box collapses the footer and drops `esc to interrupt`,
  // so this really is the mid-turn regime.
  const p = boxWith(NOTE)
  assert.ok(!/esc to interrupt/.test(p), 'footer collapsed: this is the delivered-draft frame')
  assert.equal(deliveryLanded(p, NOTE), true)
})

test('the swallow is STILL refused — a short residue is not a scrolled box', () => {
  // The incident residue IS a suffix of the payload, so "the box shows the
  // tail" cannot be the test on its own. What separates them is depth: a
  // correctly scrolled box is at its 7-8 row capacity, this one is 1 row.
  const p = boxWith(ARTIFACT)
  assert.ok(PAYLOAD.replace(/\s+/g, '').endsWith(inputBoxText(p)), 'residue is a suffix — the trap')
  assert.equal(deliveryLanded(p, PAYLOAD), false)
})

test('a fully visible payload is verified WHOLE, not just its head', () => {
  const p = boxWith('ship it when CI is green')
  assert.equal(deliveryLanded(p, 'ship it when CI is green'), true)
  // A bite out of the middle no longer passes because the front survived.
  assert.equal(deliveryLanded(p, 'ship it AFTER the migration when CI is green'), false)
})

test('leftover residue is never mistaken for the note landing', () => {
  const counted = new FakeBox()
  counted.type(NOTE)
  for (let i = 0; i < 8; i++) counted.pressClear() // the shipped counted clear
  for (const p of [counted.render(), boxWith(NOTE.slice(0, 200)), boxWith('')]) {
    assert.equal(deliveryLanded(p, NOTE), false)
  }
})

test('deliveryLanded: a collapsed paste placeholder is accepted', () => {
  // Claude Code hides a large paste behind a placeholder, so there is nothing
  // to compare — accept, which is the pre-existing behaviour (benign direction).
  assert.equal(deliveryLanded('❯ [Pasted text #1 +12 lines]', 'x'.repeat(2000)), true)
})

test('deliveryLanded: an empty payload has no head to look for', () => {
  assert.equal(deliveryLanded(EMPTY_BUSY_BOX, ''), true)
  assert.equal(deliveryLanded(EMPTY_BUSY_BOX, '   \n  '), true)
})

test('no box on the capture falls back to the whole-pane head rule', () => {
  assert.equal(deliveryLanded('some pane with no input box at all', 'hello world'), false)
  assert.equal(deliveryLanded('junk\nhello world tail\nmore', 'hello world'), true)
})

test('the verify cap stays inside one captureTail window (32 rows × 80 cols)', () => {
  assert.ok(TUI_VERIFY_MAX_CHARS > 0 && TUI_VERIFY_MAX_CHARS < 32 * 80)
})

/* --- 3. clearInputBox, against the box that behaves like the measured one - */

test('the simulator reproduces the incident under the SHIPPED counted clear', () => {
  // literal \n in the note = 0, so the shipped rule pressed C-u 8 times.
  const box = new FakeBox()
  const residue = []
  for (let attempt = 0; attempt < 4; attempt++) {
    box.type(NOTE)
    for (let i = 0; i < 8; i++) box.pressClear()
    residue.push(box.content.length)
  }
  assert.deepEqual(residue, [78, 156, 234, 312], 'one more display row survives every refusal')
  assert.ok(residue.every((n, i) => i === 0 || n > residue[i - 1]), 'unbounded growth — the incident')
})

test('a refusal leaves an EMPTY box, however many rows the payload wrapped to', async () => {
  const box = new FakeBox()
  box.type(NOTE)
  assert.ok(box.rows().length > 8, 'the note wraps past the counted clear')
  const r = await clearInputBox(box.io())
  assert.equal(r.ok, true)
  assert.equal(box.content, '', 'verified empty, not counted')
  assert.ok(r.presses >= box.presses && r.presses <= TUI_CLEAR_MAX_PRESSES)
})

test('two consecutive refusals never accumulate', async () => {
  const box = new FakeBox()
  for (let attempt = 0; attempt < 5; attempt++) {
    box.type(NOTE)
    await clearInputBox(box.io())
    assert.equal(box.content, '', `attempt ${attempt + 1} left residue`)
  }
})

test('an already-empty box costs no keystrokes', async () => {
  const r = await clearInputBox(new FakeBox().io())
  assert.equal(r.presses, 0)
  assert.equal(r.ok, true)
})

test('clearing is BOUNDED — it refuses rather than pressing C-u forever', async () => {
  const stuck = { readPane: async () => ['─'.repeat(80), '❯ ' + 'x'.repeat(40), '─'.repeat(80)].join('\n'), pressClear: async () => {} }
  const r = await clearInputBox({ ...stuck, settle: async () => {}, max: 5 })
  // Unchanging content is read as chrome we don't recognise, not as text — it
  // fails OPEN, because a gate that blocks every delivery is worse than the bug.
  assert.equal(r.ok, true)
  assert.equal(r.fixpoint, true)
  assert.ok(r.presses <= 5)
})

test('a box that keeps changing but never empties is refused at the bound', async () => {
  let n = 0
  const churn = {
    readPane: async () => ['─'.repeat(80), '❯ ' + 'x'.repeat(10) + n, '─'.repeat(80)].join('\n'),
    pressClear: async () => { n++ },
  }
  const r = await clearInputBox({ ...churn, settle: async () => {}, max: 6 })
  assert.equal(r.ok, false, 'the caller must not type into it')
  assert.equal(r.presses, 6)
})

test('the clear loop SETTLES between press and look, or lag reads as a fixpoint', async () => {
  // Measured live: without a settle the loop stopped after 1-2 presses and left
  // ~420 chars in the box — it reproduced the accumulation it exists to stop,
  // because a too-early capture returns the pre-press frame unchanged.
  const box = new FakeBox()
  box.type(NOTE)
  let settles = 0
  const lag = { pending: null }
  const io = {
    // Serve the PREVIOUS frame until a settle has happened, like a real pane.
    readPane: async () => (lag.pending === null ? box.render() : lag.pending),
    pressClear: async () => { lag.pending = box.render(); box.pressClear() },
    settle: async () => { settles++; lag.pending = null },
  }
  const r = await clearInputBox(io)
  assert.equal(r.ok, true)
  assert.equal(box.content, '', 'a lagging pane must still end empty')
  assert.ok(settles >= box.presses, 'every press is followed by a settle')
})

test('the clear key is Ctrl-U — Ctrl-C on an empty box could exit the agent', () => {
  // The box this clears is usually EMPTY, where Ctrl-C arms Claude Code's exit
  // confirm and a second one inside the 3 s flush window kills the session.
  assert.equal(TUI_CLEAR_KEY, 'C-u')
})

/* --- 4. both executors, one implementation ----------------------------- *
 * agent-local.mjs (box) and agent-bridge/server.mjs (remote) both deliver by
 * typing. A bridge kept its OWN copy of the busy rule once and a box deploy left
 * it on the old one; the same must not happen here.
 * ⚠️ A bridge only picks this up when THAT machine restarts its bridge service
 * — merging changes nothing on a bridge.
 */
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const executors = {
  box: fs.readFileSync(path.join(root, 'api', 'src', 'agent-local.mjs'), 'utf8'),
  bridge: fs.readFileSync(path.join(root, 'agent-bridge', 'server.mjs'), 'utf8'),
}

for (const [name, src] of Object.entries(executors)) {
  test(`${name}: clears via the shared verified loop, never a counted burst`, () => {
    assert.match(src, /import \{[^}]*clearInputBox[^}]*\} from '[^']*tui-input\.mjs'/)
    assert.doesNotMatch(src, /clearInputKeys/, 'counting presses is the bug')
    // Pre-type AND post-refusal: residue must never survive either path.
    assert.equal((src.match(/await clearInputBox\(io\)/g) || []).length, 2)
  })

  test(`${name}: reads the box back with SGR kept, or the placeholder reads as text`, () => {
    assert.match(src, /readPane: \(\) => captureTail\(s, TAIL_LINES, true\)/)
    assert.match(src, /deliveryLanded\(await captureTail\(s, TAIL_LINES, true\), payload\)/)
  })

  test(`${name}: the gate is one env var away from the unconditional-Enter behaviour`, () => {
    assert.match(src, /if \(TUI_VERIFY\) \{/, 'pre-type clear is behind the switch')
    assert.match(src, /if \(TUI_VERIFY && safe\.length <= TUI_VERIFY_MAX_CHARS/, 'so is the verify')
    // Sanitising is NOT behind it — it is the actual fix for the swallow.
    assert.match(src, /const safe = sanitizeForTyping\(payload\)/)
  })

  test(`${name}: a refused head backs off instead of retrying every tick`, () => {
    assert.match(src, /if \(s\.deliverRetryAt && Date\.now\(\) < s\.deliverRetryAt\) continue/)
    assert.match(src, /deliveryBackoffMs\(s\.deliverFailures\)/)
    assert.match(src, /delete s\.deliverFailures/, 'a success clears the counter')
  })
}
