#!/usr/bin/env bash
# Install the on-box prerequisites for the news-ingest addon.
# See this directory's README.md — especially the cost section, because this is
# the one addon that spends your Claude subscription on a TIMER.
#
# Installs (idempotent — re-running skips what is already there):
#   - feeds.json                     seeded from feeds.example.json, then YOURS
#   - .claude/skills/news-ingest  →  a relative symlink to this addon's skill
#   - $STATE_DIR/news-ingest.env.sample   the .env lines to paste
#   - /etc/cron.d/atlas-kit-addons   the hourly sweep (needs root; skipped otherwise)
#
# WHAT IT WILL NEVER DO: pick your feeds, or overwrite a feeds.json you already
# edited. It seeds the file once and then leaves it alone.
#
# MODES
#   (no args)  install now
#   --check    report state without changing anything:
#                exit 0 — installed
#                exit 2 — not installed, and installable right now
#                exit 1 — not installed and cannot be (reason on stderr)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DIR="$ROOT/addons/news-ingest"
STATE_DIR="${AGENT_LOCAL_DIR:-$HOME/.atlas-kit}"
FEEDS="${ATLAS_NEWS_FEEDS_FILE:-$DIR/feeds.json}"
SKILL_LINK="$ROOT/.claude/skills/news-ingest"
SAMPLE="$STATE_DIR/news-ingest.env.sample"

log() { echo "[news-ingest] $*"; }

skill_linked() { [ -L "$SKILL_LINK" ] && [ -e "$SKILL_LINK" ]; }

# "Configured" means a feed list that parses and holds at least one entry — an
# empty or broken feeds.json is exactly the state the operator needs told about,
# so it must not read as installed. node is the same parser the addon uses.
feeds_ok() {
  [ -f "$FEEDS" ] || return 1
  ATLAS_NEWS_FEEDS_FILE="$FEEDS" node --input-type=module -e "
import { loadFeeds } from '$DIR/api/feeds.mjs'
const { feeds, errors } = loadFeeds()
for (const e of errors) console.error('  ! ' + e)
process.exit(feeds.length ? 0 : 1)
"
}

installable() {
  command -v node >/dev/null 2>&1 && return 0
  echo "!! node is required" >&2
  return 1
}

seed_feeds() {
  if [ -f "$FEEDS" ]; then
    log "feed list present → $FEEDS (left untouched)"
    return 0
  fi
  cp "$DIR/feeds.example.json" "$FEEDS"
  log "seeded $FEEDS from feeds.example.json — EDIT IT: the example is a placeholder, not a reading list"
}

# A relative link, so moving or re-cloning the repo does not strand it. An
# existing REAL directory is left alone: clobbering something the operator wrote
# is never this script's call.
link_skill() {
  mkdir -p "$ROOT/.claude/skills"
  if [ -e "$SKILL_LINK" ] && [ ! -L "$SKILL_LINK" ]; then
    echo "!! $SKILL_LINK exists and is not a symlink — left untouched" >&2
    return 0
  fi
  ln -sfn ../../addons/news-ingest/skills/news-ingest "$SKILL_LINK"
  log "skill linked → .claude/skills/news-ingest"
}

write_sample() {
  mkdir -p "$STATE_DIR"
  chmod 700 "$STATE_DIR" 2>/dev/null || true
  cat > "$SAMPLE" <<EOF
# addons/news-ingest — paste the lines you need into your .env, then
# \`scripts/serve.sh restart\`. Generated by install.sh on $(date -u +%Y-%m-%d).
ATLAS_ADDONS=news-ingest

# The caps are the cost control — every NEW item is one \`claude -p\` call.
# ATLAS_NEWS_MAX_ITEMS=12        # per sweep, across all feeds
# ATLAS_NEWS_MAX_PER_FEED=5      # so one busy feed cannot eat the run
# ATLAS_NEWS_MODEL=claude-sonnet-5
# ATLAS_NEWS_VAULT=atlas         # which vault the pages land in
EOF
  chmod 600 "$SAMPLE" 2>/dev/null || true
  log "config stub → $SAMPLE"
}

# --- the cron entry ---------------------------------------------------------
# Declared in api/register.mjs and materialised by scripts/addon-cron.mjs, so
# there is exactly one place the schedule is written down. Needs root; a non-root
# install is still a valid install, it just leaves the sweep to the operator.
wire_cron() {
  if [ "$(id -u)" != 0 ]; then
    log "not root — skipping cron. Wire the sweep yourself:"
    log "    sudo ATLAS_ADDONS=news-ingest node $ROOT/scripts/addon-cron.mjs --install"
    return 0
  fi
  # ⚠️ The generated file holds the entries of EVERY enabled addon, so the
  # default here is the operator's real ATLAS_ADDONS — passing only this addon's
  # name would drop another addon's line on the way past.
  ATLAS_ADDONS="${ATLAS_ADDONS:-news-ingest}" node "$ROOT/scripts/addon-cron.mjs" --install
}

case "${1:-}" in
  --check)
    missing=""
    feeds_ok || missing="feeds.json"
    skill_linked || missing="${missing:+$missing, }skill link"
    if [ -z "$missing" ]; then
      echo "installed: $FEEDS, skill linked"
      exit 0
    fi
    installable || exit 1
    echo "not installed: $missing"
    exit 2
    ;;

  '')
    installable || exit 1
    seed_feeds
    link_skill
    write_sample
    wire_cron
    echo
    echo "Next:"
    echo "  1. put YOUR feeds in $FEEDS  (the example is a placeholder)"
    echo "  2. paste what you need from $SAMPLE into .env"
    echo "  3. restart the API:   scripts/serve.sh restart"
    echo "  4. sweep once now:    bash addons/news-ingest/sweep.sh"
    ;;

  *)
    echo "usage: install.sh [--check]" >&2
    exit 2
    ;;
esac
