#!/usr/bin/env bash
# Install the on-box prerequisites for the instagram-ingest addon.
# See this directory's README.md — especially the cookie section, which is the
# one step this script deliberately does NOT do for you.
#
# Installs (idempotent — re-running skips what is already there):
#   - yt-dlp                        via pipx, else pip --user, else the standalone
#                                   binary into $STATE_DIR/bin  (~30 MB)
#   - .claude/skills/instagram-ingest → a relative symlink to this addon's skill
#   - $STATE_DIR/instagram-ingest.env.sample  the .env lines to paste, filled in
#
# WHAT IT WILL NEVER DO: touch your cookies. Exporting a browser session is your
# decision, on your machine, and the file belongs OUTSIDE this repo — see README.
#
# MODES
#   (no args)  install now
#   --check    report state without installing anything:
#                exit 0 — installed
#                exit 2 — not installed, and installable right now
#                exit 1 — not installed and cannot be (reason on stderr)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATE_DIR="${AGENT_LOCAL_DIR:-$HOME/.atlas-kit}"
BIN_DIR="$STATE_DIR/bin"
SKILL_LINK="$ROOT/.claude/skills/instagram-ingest"
SAMPLE="$STATE_DIR/instagram-ingest.env.sample"
YTDLP_RELEASE="${ATLAS_IG_YTDLP_URL:-https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux}"

log() { echo "[instagram-ingest] $*"; }

# Honours ATLAS_IG_YTDLP (a pipx/venv install is often off the service PATH),
# which is exactly what the addon's own lookup does.
ytdlp_bin() {
  if [ -n "${ATLAS_IG_YTDLP:-}" ]; then
    command -v "$ATLAS_IG_YTDLP" 2>/dev/null || { [ -x "$ATLAS_IG_YTDLP" ] && echo "$ATLAS_IG_YTDLP"; }
  else
    command -v yt-dlp 2>/dev/null || { [ -x "$BIN_DIR/yt-dlp" ] && echo "$BIN_DIR/yt-dlp"; }
  fi
}

skill_linked() { [ -L "$SKILL_LINK" ] && [ -e "$SKILL_LINK" ]; }

installable() {
  command -v pipx >/dev/null 2>&1 && return 0
  command -v pip3 >/dev/null 2>&1 && return 0
  command -v python3 >/dev/null 2>&1 && return 0
  command -v curl >/dev/null 2>&1 && return 0
  echo "!! need one of pipx, pip3, python3 or curl to install yt-dlp" >&2
  return 1
}

install_ytdlp() {
  if [ -n "$(ytdlp_bin)" ]; then
    log "yt-dlp present → $(ytdlp_bin)"
    return 0
  fi
  if command -v pipx >/dev/null 2>&1; then
    log "installing yt-dlp with pipx"
    pipx install yt-dlp && return 0
    echo "!! pipx install failed, trying the next method" >&2
  fi
  if command -v pip3 >/dev/null 2>&1; then
    log "installing yt-dlp with pip3 --user"
    if pip3 install --user --upgrade yt-dlp; then return 0; fi
    echo "!! pip3 install failed, trying the standalone binary" >&2
  elif command -v python3 >/dev/null 2>&1; then
    log "installing yt-dlp with python3 -m pip --user"
    if python3 -m pip install --user --upgrade yt-dlp; then return 0; fi
    echo "!! pip install failed, trying the standalone binary" >&2
  fi
  if command -v curl >/dev/null 2>&1; then
    log "downloading the standalone yt-dlp binary → $BIN_DIR/yt-dlp"
    mkdir -p "$BIN_DIR"
    # .part + mv: a half-downloaded binary must never be mistaken for a working one.
    if curl -fsSL --retry 3 -o "$BIN_DIR/yt-dlp.part" "$YTDLP_RELEASE"; then
      chmod +x "$BIN_DIR/yt-dlp.part"
      mv "$BIN_DIR/yt-dlp.part" "$BIN_DIR/yt-dlp"
      log "installed. It is NOT on your PATH — set ATLAS_IG_YTDLP=$BIN_DIR/yt-dlp in .env"
      return 0
    fi
    rm -f "$BIN_DIR/yt-dlp.part"
  fi
  echo "!! could not install yt-dlp by any method" >&2
  return 1
}

# A relative link, so moving or re-cloning the repo does not strand it. An
# existing REAL directory is left alone: clobbering something the operator wrote
# is never this script's call.
link_skill() {
  mkdir -p "$ROOT/.claude/skills"
  if [ -e "$SKILL_LINK" ] && [ ! -L "$SKILL_LINK" ]; then
    echo "!! $SKILL_LINK exists and is not a symlink — left untouched" >&2
    return 0
  fi
  ln -sfn ../../addons/instagram-ingest/skills/instagram-ingest "$SKILL_LINK"
  log "skill linked → .claude/skills/instagram-ingest"
}

write_sample() {
  mkdir -p "$STATE_DIR"
  chmod 700 "$STATE_DIR" 2>/dev/null || true
  local bin; bin="$(ytdlp_bin || true)"
  cat > "$SAMPLE" <<EOF
# addons/instagram-ingest — paste the lines you need into your .env, then
# \`scripts/serve.sh restart\`. Generated by install.sh on $(date -u +%Y-%m-%d).
ATLAS_ADDONS=instagram-ingest
$([ -n "$bin" ] && [ "$bin" = "$BIN_DIR/yt-dlp" ] && echo "ATLAS_IG_YTDLP=$bin" || echo "# ATLAS_IG_YTDLP=/path/to/yt-dlp   # only if it is off the service PATH")

# YOUR OWN session — pick ONE. Never commit either of these; see the addon README.
# ATLAS_IG_COOKIES_FILE=$STATE_DIR/instagram-cookies.txt
# ATLAS_IG_COOKIES_BROWSER=firefox

# ATLAS_IG_MODEL=claude-sonnet-5
EOF
  chmod 600 "$SAMPLE" 2>/dev/null || true
  log "config stub → $SAMPLE"
}

case "${1:-}" in
  --check)
    missing=""
    [ -n "$(ytdlp_bin)" ] || missing="yt-dlp"
    skill_linked || missing="${missing:+$missing, }skill link"
    if [ -z "$missing" ]; then
      echo "installed: yt-dlp $(ytdlp_bin), skill linked"
      [ -n "${ATLAS_IG_COOKIES_FILE:-}${ATLAS_IG_COOKIES_BROWSER:-}" ] ||
        echo "note: no cookies configured — most posts will hit Instagram's login wall (see README.md)"
      exit 0
    fi
    installable || exit 1
    echo "not installed: $missing"
    exit 2
    ;;

  '')
    installable || exit 1
    install_ytdlp || exit 1
    link_skill
    write_sample
    echo
    echo "Next:"
    echo "  1. export YOUR OWN Instagram cookies — addons/instagram-ingest/README.md"
    echo "     (keep the file outside this repo; it is a live login session)"
    echo "  2. paste what you need from $SAMPLE into .env"
    echo "  3. restart the API:   scripts/serve.sh restart"
    echo "  4. ingest one post:   curl -s -X POST http://127.0.0.1:3001/api/ingest/instagram \\"
    echo "                          -H \"Authorization: Bearer \$DASHBOARD_BEARER_TOKEN\" \\"
    echo "                          -H 'content-type: application/json' \\"
    echo "                          -d '{\"url\":\"https://www.instagram.com/p/<code>/\"}'"
    ;;

  *)
    echo "usage: install.sh [--check]" >&2
    exit 2
    ;;
esac
