#!/usr/bin/env bash
# Wire up the OPTIONAL on-box engines for the voice addon. See this directory's
# README.md — especially the cost and privacy sections.
#
# 🔴 THE ADDON NEEDS NONE OF THIS. Enable `voice` and the dashboard already
# speaks (the browser's speechSynthesis) and already listens (its Web Speech
# API): no download, no key, no server round-trip. This script exists for the two
# cases the browser cannot cover — a browser with no Web Speech API, and an
# operator who wants the audio never to leave the box.
#
# Installs (idempotent — re-running skips what is already there):
#   - $STATE_DIR/voice.env.sample     the .env lines to paste, filled in with
#                                     whatever engines this box actually has
#   --engine espeak-ng                apt-get espeak-ng (~5 MB) → TTS command
#   --engine piper                    a venv + piper-tts + one voice (~250 MB)
#   --engine whisper                  an STT wrapper around an EXISTING
#                                     whisper.cpp + ffmpeg (installs neither)
#
# WHAT IT WILL NEVER DO: edit your .env, pick your voice, or install a model you
# did not ask for by name. It prints the two lines you paste, and stops.
#
# MODES
#   (no args)  detect what is here, write the sample, install nothing
#   --engine <espeak-ng|piper|whisper>   install/wire that one engine
#   --check    report state without changing anything:
#                exit 0 — ready (either no engine is configured, i.e. the browser
#                         default, or every configured one resolves)
#                exit 2 — a configured engine is missing, and installable now
#                exit 1 — a configured engine is missing and cannot be installed
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATE_DIR="${AGENT_LOCAL_DIR:-$HOME/.atlas-kit}"
DIR="${ATLAS_VOICE_DIR:-$STATE_DIR/voice}"
SAMPLE="$STATE_DIR/voice.env.sample"
PIPER_BIN="$DIR/piper/bin/piper"
VOICE_NAME="${ATLAS_VOICE_PIPER_VOICE:-en_US-amy-medium}"
VOICE_ONNX="$DIR/voices/$VOICE_NAME.onnx"
# Overridable so a mirror, an air-gapped copy or a different voice needs no patch.
VOICE_BASE="${ATLAS_VOICE_PIPER_VOICE_URL:-https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium}"
STT_WRAPPER="$DIR/stt-whisper.sh"
MIN_AVAIL_MB=600

log() { echo "[voice] $*"; }

# The first word of a configured command — what has to be executable for the
# addon to report `available: true`. Empty when nothing is configured.
cmd_bin() { echo "${1%% *}"; }

resolves() { [ -n "$1" ] && command -v "$(cmd_bin "$1")" >/dev/null 2>&1; }

disk_ok() {
  mkdir -p "$DIR" 2>/dev/null || true
  local avail
  avail=$(df -Pm "$DIR" 2>/dev/null | awk 'NR==2 {print $4}')
  if [ -z "$avail" ]; then
    echo "!! cannot read free space for $DIR" >&2
    return 1
  fi
  [ "$avail" -ge "$MIN_AVAIL_MB" ] && return 0
  echo "!! only ${avail} MB free — need ~${MIN_AVAIL_MB} MB for a venv + a voice" >&2
  return 1
}

# What this box could speak/listen with right now, whether or not it is configured.
detect() {
  local found=""
  [ -x "$PIPER_BIN" ] && found="$found  piper (this addon's venv):        ATLAS_VOICE_TTS_CMD=\"$PIPER_BIN -m $VOICE_ONNX -f -\"\n"
  command -v piper >/dev/null 2>&1 && found="$found  piper (on PATH):                 ATLAS_VOICE_TTS_CMD=\"piper -m /path/to/voice.onnx -f -\"\n"
  command -v espeak-ng >/dev/null 2>&1 && found="$found  espeak-ng (robotic but tiny):    ATLAS_VOICE_TTS_CMD=\"espeak-ng --stdout\"\n"
  [ -x "$STT_WRAPPER" ] && found="$found  whisper.cpp wrapper:             ATLAS_VOICE_STT_CMD=\"$STT_WRAPPER {file}\"\n"
  printf '%b' "$found"
}

write_sample() {
  mkdir -p "$STATE_DIR"
  chmod 700 "$STATE_DIR" 2>/dev/null || true
  {
    cat <<EOF
# addons/voice — paste the lines you need into your .env, then
# \`scripts/serve.sh restart\`. Generated by install.sh on $(date -u +%Y-%m-%d).
ATLAS_ADDONS=voice

# NOTHING BELOW IS REQUIRED. With no engine configured the browser speaks and
# listens, which is the zero-install default the addon is designed around.
EOF
    local d
    d="$(detect)"
    if [ -n "$d" ]; then
      echo "#"
      echo "# Engines found on this box:"
      printf '%s' "$d" | sed 's/^/# /'
    else
      echo "#"
      echo "# No on-box engine found. Add one with:  bash addons/voice/install.sh --engine espeak-ng"
    fi
    cat <<'EOF'
#
# ATLAS_VOICE_MODEL=claude-haiku-4-5   # the model that writes a spoken recap
# ATLAS_VOICE_DAILY_BUDGET=100         # recap calls per day, across the fleet
# ATLAS_VOICE_MIN_INTERVAL_MS=60000    # …and per agent
#
# The dashboard reaches POST /api/voice/* only through the reverse proxy, which
# is where the bearer token is injected. Add this to infra/Caddyfile:
#   handle /api/voice/* {
#     reverse_proxy localhost:3001 {
#       header_up Authorization "Bearer {env.DASHBOARD_BEARER_TOKEN}"
#     }
#   }
EOF
  } > "$SAMPLE"
  chmod 600 "$SAMPLE" 2>/dev/null || true
  log "config stub → $SAMPLE"
}

install_espeak() {
  if command -v espeak-ng >/dev/null 2>&1; then
    log "espeak-ng is already installed"
  else
    command -v apt-get >/dev/null 2>&1 || {
      echo "!! no apt-get here — install espeak-ng with your own package manager" >&2
      exit 1
    }
    [ "$(id -u)" = 0 ] || {
      echo "!! needs root:  sudo bash addons/voice/install.sh --engine espeak-ng" >&2
      exit 1
    }
    apt-get update -qq && apt-get install -y -qq espeak-ng
  fi
  echo 'test' | espeak-ng --stdout > /dev/null || {
    echo "!! espeak-ng is installed but produced no audio" >&2
    exit 1
  }
  log 'ready → ATLAS_VOICE_TTS_CMD="espeak-ng --stdout"'
}

install_piper() {
  disk_ok || exit 1
  if [ ! -x "$PIPER_BIN" ]; then
    command -v python3 >/dev/null 2>&1 || {
      echo "!! python3 is required for piper" >&2
      exit 1
    }
    log "creating a venv at $DIR/piper (~250 MB with onnxruntime)"
    python3 -m venv "$DIR/piper"
    "$DIR/piper/bin/pip" install --quiet --upgrade pip
    "$DIR/piper/bin/pip" install --quiet piper-tts
  else
    log "piper venv present → $PIPER_BIN"
  fi
  mkdir -p "$DIR/voices"
  if [ ! -s "$VOICE_ONNX" ]; then
    log "downloading voice $VOICE_NAME (~60 MB)"
    curl -fSL --retry 2 -o "$VOICE_ONNX" "$VOICE_BASE/$VOICE_NAME.onnx" || {
      rm -f "$VOICE_ONNX"
      echo "!! could not download $VOICE_BASE/$VOICE_NAME.onnx — set ATLAS_VOICE_PIPER_VOICE_URL to a mirror, or drop the .onnx + .onnx.json into $DIR/voices yourself" >&2
      exit 1
    }
    curl -fSL --retry 2 -o "$VOICE_ONNX.json" "$VOICE_BASE/$VOICE_NAME.onnx.json" || {
      rm -f "$VOICE_ONNX" "$VOICE_ONNX.json"
      echo "!! the voice config did not download — removed the half-installed voice" >&2
      exit 1
    }
  else
    log "voice present → $VOICE_ONNX"
  fi
  # Prove it before telling the operator to configure it: a command line that
  # does not actually synthesize is worse than no command line.
  echo 'test' | "$PIPER_BIN" -m "$VOICE_ONNX" -f - > /dev/null 2>&1 || {
    echo "!! piper is installed but did not synthesize — see $DIR/piper" >&2
    exit 1
  }
  log "ready → ATLAS_VOICE_TTS_CMD=\"$PIPER_BIN -m $VOICE_ONNX -f -\""
}

# whisper.cpp is a build, not a package, so this INSTALLS NOTHING: it writes the
# wrapper that turns the browser's webm/opus clip into the 16 kHz mono wav
# whisper wants, around a whisper-cli and a model you already have.
install_whisper_wrapper() {
  local model="${WHISPER_MODEL:-}"
  command -v whisper-cli >/dev/null 2>&1 || {
    echo "!! whisper-cli is not on PATH — build whisper.cpp first, then re-run this" >&2
    exit 1
  }
  command -v ffmpeg >/dev/null 2>&1 || {
    echo "!! ffmpeg is required to decode the browser's clip" >&2
    exit 1
  }
  [ -s "$model" ] || {
    echo "!! set WHISPER_MODEL to your ggml model:  WHISPER_MODEL=/path/ggml-base.en.bin bash addons/voice/install.sh --engine whisper" >&2
    exit 1
  }
  mkdir -p "$DIR"
  cat > "$STT_WRAPPER" <<EOF
#!/bin/sh
# Generated by addons/voice/install.sh — browser clip → 16 kHz wav → whisper.cpp.
# Called as: $STT_WRAPPER <clip>   (the addon substitutes {file})
set -e
wav="\$(mktemp -t atlas-kit-stt-XXXXXX.wav)"
trap 'rm -f "\$wav"' EXIT
ffmpeg -loglevel error -y -i "\$1" -ar 16000 -ac 1 "\$wav"
whisper-cli -m "$model" -f "\$wav" -nt 2>/dev/null
EOF
  chmod 700 "$STT_WRAPPER"
  log "ready → ATLAS_VOICE_STT_CMD=\"$STT_WRAPPER {file}\""
}

case "${1:-}" in
  --check)
    rc=0
    for var in ATLAS_VOICE_TTS_CMD ATLAS_VOICE_STT_CMD; do
      cmd="${!var:-}"
      if [ -z "$cmd" ]; then
        echo "$var unset — the browser handles it (zero-install default)"
      elif resolves "$cmd"; then
        echo "$var ok → $(cmd_bin "$cmd")"
      else
        echo "$var names $(cmd_bin "$cmd"), which is not executable here" >&2
        rc=2
      fi
    done
    if [ "$rc" = 2 ] && ! command -v apt-get >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1; then
      echo "!! and neither apt-get nor python3 is here to install one" >&2
      exit 1
    fi
    exit "$rc"
    ;;

  --engine)
    case "${2:-}" in
      espeak-ng) install_espeak ;;
      piper) install_piper ;;
      whisper) install_whisper_wrapper ;;
      *)
        echo "usage: install.sh --engine <espeak-ng|piper|whisper>" >&2
        exit 2
        ;;
    esac
    write_sample
    echo
    echo "Next: paste the ATLAS_VOICE_* line above into .env, then  scripts/serve.sh restart"
    ;;

  '')
    write_sample
    echo
    found="$(detect)"
    if [ -n "$found" ]; then
      echo "On-box engines available here:"
      printf '%b' "$found"
    else
      echo "No on-box engine here — the browser speaks and listens, which needs nothing."
      echo "Want one anyway?  bash addons/voice/install.sh --engine espeak-ng   (tiny, offline)"
      echo "                  bash addons/voice/install.sh --engine piper       (~250 MB, natural)"
    fi
    echo
    echo "Next:"
    echo "  1. add  ATLAS_ADDONS=voice  to .env  (see $SAMPLE)"
    echo "  2. add the /api/voice/* handler to infra/Caddyfile — see the sample and the README"
    echo "  3. restart:  scripts/serve.sh restart"
    ;;

  *)
    echo "usage: install.sh [--check | --engine <espeak-ng|piper|whisper>]" >&2
    exit 2
    ;;
esac
